/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Title from './Title';

/**
 * The APIModelsLandlordMember model module.
 * @module model/APIModelsLandlordMember
 * @version 1.2.2
 */
class APIModelsLandlordMember {
    /**
     * Constructs a new <code>APIModelsLandlordMember</code>.
     * Model for a new landlord member
     * @alias module:model/APIModelsLandlordMember
     * @param landlordType {String} Private / Corporate
     * @param title {module:model/Title} 
     * @param firstName {String} Must be 50 characters or less
     * @param lastName {String} Must be 50 characters or less
     * @param addressLine1 {String} Must be 100 characters or less
     * @param postcode {String} Must be 8 characters or less
     * @param countryCode {String} This is required for Custodial, and must be GB for Insurance
     * @param emailAddress {String} Must be 100 characters or less
     */
    constructor(landlordType, title, firstName, lastName, addressLine1, postcode, countryCode, emailAddress) { 
        
        APIModelsLandlordMember.initialize(this, landlordType, title, firstName, lastName, addressLine1, postcode, countryCode, emailAddress);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, landlordType, title, firstName, lastName, addressLine1, postcode, countryCode, emailAddress) { 
        obj['landlordType'] = landlordType;
        obj['title'] = title;
        obj['firstName'] = firstName;
        obj['lastName'] = lastName;
        obj['addressLine1'] = addressLine1;
        obj['postcode'] = postcode;
        obj['countryCode'] = countryCode;
        obj['emailAddress'] = emailAddress;
    }

    /**
     * Constructs a <code>APIModelsLandlordMember</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIModelsLandlordMember} obj Optional instance to populate.
     * @return {module:model/APIModelsLandlordMember} The populated <code>APIModelsLandlordMember</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIModelsLandlordMember();

            if (data.hasOwnProperty('landlordType')) {
                obj['landlordType'] = ApiClient.convertToType(data['landlordType'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = Title.constructFromObject(data['title']);
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('addressLine1')) {
                obj['addressLine1'] = ApiClient.convertToType(data['addressLine1'], 'String');
            }
            if (data.hasOwnProperty('addressLine2')) {
                obj['addressLine2'] = ApiClient.convertToType(data['addressLine2'], 'String');
            }
            if (data.hasOwnProperty('addressLine3')) {
                obj['addressLine3'] = ApiClient.convertToType(data['addressLine3'], 'String');
            }
            if (data.hasOwnProperty('addressLine4')) {
                obj['addressLine4'] = ApiClient.convertToType(data['addressLine4'], 'String');
            }
            if (data.hasOwnProperty('postcode')) {
                obj['postcode'] = ApiClient.convertToType(data['postcode'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('companyRegistrationNumber')) {
                obj['companyRegistrationNumber'] = ApiClient.convertToType(data['companyRegistrationNumber'], 'String');
            }
            if (data.hasOwnProperty('registeredAddressLine1')) {
                obj['registeredAddressLine1'] = ApiClient.convertToType(data['registeredAddressLine1'], 'String');
            }
            if (data.hasOwnProperty('registeredAddressLine2')) {
                obj['registeredAddressLine2'] = ApiClient.convertToType(data['registeredAddressLine2'], 'String');
            }
            if (data.hasOwnProperty('registeredAddressLine3')) {
                obj['registeredAddressLine3'] = ApiClient.convertToType(data['registeredAddressLine3'], 'String');
            }
            if (data.hasOwnProperty('registeredPostcode')) {
                obj['registeredPostcode'] = ApiClient.convertToType(data['registeredPostcode'], 'String');
            }
            if (data.hasOwnProperty('homeTelephone')) {
                obj['homeTelephone'] = ApiClient.convertToType(data['homeTelephone'], 'String');
            }
            if (data.hasOwnProperty('mobileTelephone')) {
                obj['mobileTelephone'] = ApiClient.convertToType(data['mobileTelephone'], 'String');
            }
            if (data.hasOwnProperty('workTelephone')) {
                obj['workTelephone'] = ApiClient.convertToType(data['workTelephone'], 'String');
            }
            if (data.hasOwnProperty('branchTelephone')) {
                obj['branchTelephone'] = ApiClient.convertToType(data['branchTelephone'], 'String');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('workEmailAddress')) {
                obj['workEmailAddress'] = ApiClient.convertToType(data['workEmailAddress'], 'String');
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Private / Corporate
 * @member {String} landlordType
 */
APIModelsLandlordMember.prototype['landlordType'] = undefined;

/**
 * @member {module:model/Title} title
 */
APIModelsLandlordMember.prototype['title'] = undefined;

/**
 * Must be 50 characters or less
 * @member {String} firstName
 */
APIModelsLandlordMember.prototype['firstName'] = undefined;

/**
 * Must be 50 characters or less
 * @member {String} lastName
 */
APIModelsLandlordMember.prototype['lastName'] = undefined;

/**
 * Must be 100 characters or less
 * @member {String} addressLine1
 */
APIModelsLandlordMember.prototype['addressLine1'] = undefined;

/**
 * Must be 100 characters or less
 * @member {String} addressLine2
 */
APIModelsLandlordMember.prototype['addressLine2'] = undefined;

/**
 * Must be 90 characters or less
 * @member {String} addressLine3
 */
APIModelsLandlordMember.prototype['addressLine3'] = undefined;

/**
 * Must be 80 characters or less
 * @member {String} addressLine4
 */
APIModelsLandlordMember.prototype['addressLine4'] = undefined;

/**
 * Must be 8 characters or less
 * @member {String} postcode
 */
APIModelsLandlordMember.prototype['postcode'] = undefined;

/**
 * This is required for Custodial, and must be GB for Insurance
 * @member {String} countryCode
 */
APIModelsLandlordMember.prototype['countryCode'] = undefined;

/**
 * Required for corporate landlords Must be 100 characters or less 
 * @member {String} companyName
 */
APIModelsLandlordMember.prototype['companyName'] = undefined;

/**
 * Must be 15 characters or less
 * @member {String} companyRegistrationNumber
 */
APIModelsLandlordMember.prototype['companyRegistrationNumber'] = undefined;

/**
 * Required for Insurance corporate landlords only Must be 100 characters or less 
 * @member {String} registeredAddressLine1
 */
APIModelsLandlordMember.prototype['registeredAddressLine1'] = undefined;

/**
 * Must be 100 characters or less
 * @member {String} registeredAddressLine2
 */
APIModelsLandlordMember.prototype['registeredAddressLine2'] = undefined;

/**
 * Must be 100 characters or less
 * @member {String} registeredAddressLine3
 */
APIModelsLandlordMember.prototype['registeredAddressLine3'] = undefined;

/**
 * Required for Insurance corporate landlords only Must be 8 characters or less 
 * @member {String} registeredPostcode
 */
APIModelsLandlordMember.prototype['registeredPostcode'] = undefined;

/**
 * Private landlords - must provide either a home or mobile phone number Corporate landlords (Custodial) - must provide either a home or mobile phone number Must be 15 characters or less 
 * @member {String} homeTelephone
 */
APIModelsLandlordMember.prototype['homeTelephone'] = undefined;

/**
 * Private landlords - must provide either a home or mobile phone number Corporate landlords (Custodial) - must provide either a home or mobile phone number Corporate landlords (Insurance) - must provide either a work or mobile phone number Must be 15 characters or less 
 * @member {String} mobileTelephone
 */
APIModelsLandlordMember.prototype['mobileTelephone'] = undefined;

/**
 * Corporate landlords (Insurance) - must provide either a work or mobile phone number Must be 15 characters or less 
 * @member {String} workTelephone
 */
APIModelsLandlordMember.prototype['workTelephone'] = undefined;

/**
 * For Custodial corporate landlords only - must provide a branch phone number Must be 15 characters or less 
 * @member {String} branchTelephone
 */
APIModelsLandlordMember.prototype['branchTelephone'] = undefined;

/**
 * Must be 100 characters or less
 * @member {String} emailAddress
 */
APIModelsLandlordMember.prototype['emailAddress'] = undefined;

/**
 * Required for Corporate Custodial members only. ust be 255 characters or less 
 * @member {String} workEmailAddress
 */
APIModelsLandlordMember.prototype['workEmailAddress'] = undefined;

/**
 * Required for private landlords (E&W Insurance + Custodial) and for corporate landlords (E&W Custodial only). Must be at least 16 years old to join the scheme. Must be in the format dd/mm/yyyy. Must be 10 characters 
 * @member {String} dateOfBirth
 */
APIModelsLandlordMember.prototype['dateOfBirth'] = undefined;






export default APIModelsLandlordMember;

