/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIModelsSubscribe model module.
 * @module model/APIModelsSubscribe
 * @version 1.2.2
 */
class APIModelsSubscribe {
    /**
     * Constructs a new <code>APIModelsSubscribe</code>.
     * Model for a new member scheme subscription
     * @alias module:model/APIModelsSubscribe
     * @param schemeRulesAccepted {String} Must be 'true' to subscribe to the scheme by accepting its Terms and Conditions
     */
    constructor(schemeRulesAccepted) { 
        
        APIModelsSubscribe.initialize(this, schemeRulesAccepted);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, schemeRulesAccepted) { 
        obj['schemeRulesAccepted'] = schemeRulesAccepted;
    }

    /**
     * Constructs a <code>APIModelsSubscribe</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIModelsSubscribe} obj Optional instance to populate.
     * @return {module:model/APIModelsSubscribe} The populated <code>APIModelsSubscribe</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIModelsSubscribe();

            if (data.hasOwnProperty('schemeRulesAccepted')) {
                obj['schemeRulesAccepted'] = ApiClient.convertToType(data['schemeRulesAccepted'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Must be 'true' to subscribe to the scheme by accepting its Terms and Conditions
 * @member {String} schemeRulesAccepted
 */
APIModelsSubscribe.prototype['schemeRulesAccepted'] = undefined;






export default APIModelsSubscribe;

