/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIModelsPaymentDetail model module.
 * @module model/APIModelsPaymentDetail
 * @version 1.2.2
 */
class APIModelsPaymentDetail {
    /**
     * Constructs a new <code>APIModelsPaymentDetail</code>.
     * An object holding information on how a deposit should be repaid to a member
     * @alias module:model/APIModelsPaymentDetail
     * @param beneficiaryName {String} The name on the bank account, must be 75 characters or less
     * @param bankAccountNumber {String} Must be an 8 digit number
     * @param bankSortCode {String} Must be a 6 digit number
     */
    constructor(beneficiaryName, bankAccountNumber, bankSortCode) { 
        
        APIModelsPaymentDetail.initialize(this, beneficiaryName, bankAccountNumber, bankSortCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, beneficiaryName, bankAccountNumber, bankSortCode) { 
        obj['beneficiaryName'] = beneficiaryName;
        obj['bankAccountNumber'] = bankAccountNumber;
        obj['bankSortCode'] = bankSortCode;
    }

    /**
     * Constructs a <code>APIModelsPaymentDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIModelsPaymentDetail} obj Optional instance to populate.
     * @return {module:model/APIModelsPaymentDetail} The populated <code>APIModelsPaymentDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIModelsPaymentDetail();

            if (data.hasOwnProperty('beneficiaryName')) {
                obj['beneficiaryName'] = ApiClient.convertToType(data['beneficiaryName'], 'String');
            }
            if (data.hasOwnProperty('bankAccountNumber')) {
                obj['bankAccountNumber'] = ApiClient.convertToType(data['bankAccountNumber'], 'String');
            }
            if (data.hasOwnProperty('bankSortCode')) {
                obj['bankSortCode'] = ApiClient.convertToType(data['bankSortCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name on the bank account, must be 75 characters or less
 * @member {String} beneficiaryName
 */
APIModelsPaymentDetail.prototype['beneficiaryName'] = undefined;

/**
 * Must be an 8 digit number
 * @member {String} bankAccountNumber
 */
APIModelsPaymentDetail.prototype['bankAccountNumber'] = undefined;

/**
 * Must be a 6 digit number
 * @member {String} bankSortCode
 */
APIModelsPaymentDetail.prototype['bankSortCode'] = undefined;






export default APIModelsPaymentDetail;

