/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APIModelsUnprotectionDeductions from './APIModelsUnprotectionDeductions';

/**
 * The APIModelsUnprotect model module.
 * @module model/APIModelsUnprotect
 * @version 1.2.2
 */
class APIModelsUnprotect {
    /**
     * Constructs a new <code>APIModelsUnprotect</code>.
     * Tenancy model used to initiate or counter a deposit release request
     * @alias module:model/APIModelsUnprotect
     * @param tenancyEndDate {String} The date the tenant vacated the property (dd/mm/yyyy)
     * @param keyType {String} Either OTP (online portals) or PRIVATE_KEY (PMS software)
     */
    constructor(tenancyEndDate, keyType) { 
        
        APIModelsUnprotect.initialize(this, tenancyEndDate, keyType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tenancyEndDate, keyType) { 
        obj['tenancyEndDate'] = tenancyEndDate;
        obj['keyType'] = keyType;
    }

    /**
     * Constructs a <code>APIModelsUnprotect</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIModelsUnprotect} obj Optional instance to populate.
     * @return {module:model/APIModelsUnprotect} The populated <code>APIModelsUnprotect</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIModelsUnprotect();

            if (data.hasOwnProperty('tenancyEndDate')) {
                obj['tenancyEndDate'] = ApiClient.convertToType(data['tenancyEndDate'], 'String');
            }
            if (data.hasOwnProperty('keyType')) {
                obj['keyType'] = ApiClient.convertToType(data['keyType'], 'String');
            }
            if (data.hasOwnProperty('deductions')) {
                obj['deductions'] = APIModelsUnprotectionDeductions.constructFromObject(data['deductions']);
            }
        }
        return obj;
    }


}

/**
 * The date the tenant vacated the property (dd/mm/yyyy)
 * @member {String} tenancyEndDate
 */
APIModelsUnprotect.prototype['tenancyEndDate'] = undefined;

/**
 * Either OTP (online portals) or PRIVATE_KEY (PMS software)
 * @member {String} keyType
 */
APIModelsUnprotect.prototype['keyType'] = undefined;

/**
 * @member {module:model/APIModelsUnprotectionDeductions} deductions
 */
APIModelsUnprotect.prototype['deductions'] = undefined;






export default APIModelsUnprotect;

