/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APIModelsDeductions from './APIModelsDeductions';

/**
 * The APIModelsUnprotectionDeductions model module.
 * @module model/APIModelsUnprotectionDeductions
 * @version 1.2.2
 */
class APIModelsUnprotectionDeductions {
    /**
     * Constructs a new <code>APIModelsUnprotectionDeductions</code>.
     * Deductions requested for a deposit release request. Only needed if deductions are to be made
     * @alias module:model/APIModelsUnprotectionDeductions
     * @param paymentMethod {String} Must be CHEQUE or BACS
     * @param defaultPaymentID {String} Only needed for BACS payments
     * @param deduction {Array.<module:model/APIModelsDeductions>} 
     */
    constructor(paymentMethod, defaultPaymentID, deduction) { 
        
        APIModelsUnprotectionDeductions.initialize(this, paymentMethod, defaultPaymentID, deduction);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paymentMethod, defaultPaymentID, deduction) { 
        obj['paymentMethod'] = paymentMethod;
        obj['defaultPaymentID'] = defaultPaymentID;
        obj['deduction'] = deduction;
    }

    /**
     * Constructs a <code>APIModelsUnprotectionDeductions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIModelsUnprotectionDeductions} obj Optional instance to populate.
     * @return {module:model/APIModelsUnprotectionDeductions} The populated <code>APIModelsUnprotectionDeductions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIModelsUnprotectionDeductions();

            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiClient.convertToType(data['paymentMethod'], 'String');
            }
            if (data.hasOwnProperty('defaultPaymentID')) {
                obj['defaultPaymentID'] = ApiClient.convertToType(data['defaultPaymentID'], 'String');
            }
            if (data.hasOwnProperty('deduction')) {
                obj['deduction'] = ApiClient.convertToType(data['deduction'], [APIModelsDeductions]);
            }
        }
        return obj;
    }


}

/**
 * Must be CHEQUE or BACS
 * @member {String} paymentMethod
 */
APIModelsUnprotectionDeductions.prototype['paymentMethod'] = undefined;

/**
 * Only needed for BACS payments
 * @member {String} defaultPaymentID
 */
APIModelsUnprotectionDeductions.prototype['defaultPaymentID'] = undefined;

/**
 * @member {Array.<module:model/APIModelsDeductions>} deduction
 */
APIModelsUnprotectionDeductions.prototype['deduction'] = undefined;






export default APIModelsUnprotectionDeductions;

