/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIModelsCheckout model module.
 * @module model/APIModelsCheckout
 * @version 1.2.2
 */
class APIModelsCheckout {
    /**
     * Constructs a new <code>APIModelsCheckout</code>.
     * @alias module:model/APIModelsCheckout
     * @param paymentMethod {String} Must be BANK_TRANSFER
     */
    constructor(paymentMethod) { 
        
        APIModelsCheckout.initialize(this, paymentMethod);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paymentMethod) { 
        obj['paymentMethod'] = paymentMethod;
    }

    /**
     * Constructs a <code>APIModelsCheckout</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIModelsCheckout} obj Optional instance to populate.
     * @return {module:model/APIModelsCheckout} The populated <code>APIModelsCheckout</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIModelsCheckout();

            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiClient.convertToType(data['paymentMethod'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Must be BANK_TRANSFER
 * @member {String} paymentMethod
 */
APIModelsCheckout.prototype['paymentMethod'] = undefined;






export default APIModelsCheckout;

