/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesBatchTenancy model module.
 * @module model/APIResponsesBatchTenancy
 * @version 1.2.2
 */
class APIResponsesBatchTenancy {
    /**
     * Constructs a new <code>APIResponsesBatchTenancy</code>.
     * Details of a given tenancy within a batch
     * @alias module:model/APIResponsesBatchTenancy
     */
    constructor() { 
        
        APIResponsesBatchTenancy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesBatchTenancy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesBatchTenancy} obj Optional instance to populate.
     * @return {module:model/APIResponsesBatchTenancy} The populated <code>APIResponsesBatchTenancy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesBatchTenancy();

            if (data.hasOwnProperty('tenancyID')) {
                obj['tenancyID'] = ApiClient.convertToType(data['tenancyID'], 'String');
            }
            if (data.hasOwnProperty('amountInBatch')) {
                obj['amountInBatch'] = ApiClient.convertToType(data['amountInBatch'], 'Number');
            }
            if (data.hasOwnProperty('outstandingBalance')) {
                obj['outstandingBalance'] = ApiClient.convertToType(data['outstandingBalance'], 'Number');
            }
            if (data.hasOwnProperty('depositAmount')) {
                obj['depositAmount'] = ApiClient.convertToType(data['depositAmount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Our unique reference for this tenancy
 * @member {String} tenancyID
 */
APIResponsesBatchTenancy.prototype['tenancyID'] = undefined;

/**
 * The value for this tenancy that will be paid within this batch
 * @member {Number} amountInBatch
 */
APIResponsesBatchTenancy.prototype['amountInBatch'] = undefined;

/**
 * The outstanding balance for this tenancy
 * @member {Number} outstandingBalance
 */
APIResponsesBatchTenancy.prototype['outstandingBalance'] = undefined;

/**
 * The stated deposit amount for this tenancy
 * @member {Number} depositAmount
 */
APIResponsesBatchTenancy.prototype['depositAmount'] = undefined;






export default APIResponsesBatchTenancy;

