/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesErrors model module.
 * @module model/APIResponsesErrors
 * @version 1.2.2
 */
class APIResponsesErrors {
    /**
     * Constructs a new <code>APIResponsesErrors</code>.
     * @alias module:model/APIResponsesErrors
     */
    constructor() { 
        
        APIResponsesErrors.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesErrors</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesErrors} obj Optional instance to populate.
     * @return {module:model/APIResponsesErrors} The populated <code>APIResponsesErrors</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesErrors();

            if (data.hasOwnProperty('fieldName')) {
                obj['fieldName'] = ApiClient.convertToType(data['fieldName'], 'String');
            }
            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The affected field
 * @member {String} fieldName
 */
APIResponsesErrors.prototype['fieldName'] = undefined;

/**
 * The error message
 * @member {String} errorMessage
 */
APIResponsesErrors.prototype['errorMessage'] = undefined;






export default APIResponsesErrors;

