/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesBatchAddTenancy model module.
 * @module model/APIResponsesBatchAddTenancy
 * @version 1.2.2
 */
class APIResponsesBatchAddTenancy {
    /**
     * Constructs a new <code>APIResponsesBatchAddTenancy</code>.
     * @alias module:model/APIResponsesBatchAddTenancy
     */
    constructor() { 
        
        APIResponsesBatchAddTenancy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesBatchAddTenancy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesBatchAddTenancy} obj Optional instance to populate.
     * @return {module:model/APIResponsesBatchAddTenancy} The populated <code>APIResponsesBatchAddTenancy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesBatchAddTenancy();

            if (data.hasOwnProperty('batchID')) {
                obj['batchID'] = ApiClient.convertToType(data['batchID'], 'String');
            }
            if (data.hasOwnProperty('batchName')) {
                obj['batchName'] = ApiClient.convertToType(data['batchName'], 'String');
            }
            if (data.hasOwnProperty('totalAmountInBatch')) {
                obj['totalAmountInBatch'] = ApiClient.convertToType(data['totalAmountInBatch'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Our unique ID for this batch of tenancies
 * @member {String} batchID
 */
APIResponsesBatchAddTenancy.prototype['batchID'] = undefined;

/**
 * You name for this batch
 * @member {String} batchName
 */
APIResponsesBatchAddTenancy.prototype['batchName'] = undefined;

/**
 * The total monetary value of the batch of tenancies that you need to send to us via bank transfer
 * @member {Number} totalAmountInBatch
 */
APIResponsesBatchAddTenancy.prototype['totalAmountInBatch'] = undefined;

/**
 * The status of the batch. Can be checked out if \"READY_TO_PAY\"
 * @member {String} status
 */
APIResponsesBatchAddTenancy.prototype['status'] = undefined;






export default APIResponsesBatchAddTenancy;

