/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APIResponsesBatchTenancy from './APIResponsesBatchTenancy';

/**
 * The APIResponsesBatchDetails model module.
 * @module model/APIResponsesBatchDetails
 * @version 1.2.2
 */
class APIResponsesBatchDetails {
    /**
     * Constructs a new <code>APIResponsesBatchDetails</code>.
     * Details of a given batch ID
     * @alias module:model/APIResponsesBatchDetails
     */
    constructor() { 
        
        APIResponsesBatchDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesBatchDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesBatchDetails} obj Optional instance to populate.
     * @return {module:model/APIResponsesBatchDetails} The populated <code>APIResponsesBatchDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesBatchDetails();

            if (data.hasOwnProperty('batchID')) {
                obj['batchID'] = ApiClient.convertToType(data['batchID'], 'String');
            }
            if (data.hasOwnProperty('batchName')) {
                obj['batchName'] = ApiClient.convertToType(data['batchName'], 'String');
            }
            if (data.hasOwnProperty('totalAmountInBatch')) {
                obj['totalAmountInBatch'] = ApiClient.convertToType(data['totalAmountInBatch'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('tenancies')) {
                obj['tenancies'] = ApiClient.convertToType(data['tenancies'], [APIResponsesBatchTenancy]);
            }
        }
        return obj;
    }


}

/**
 * Our unique reference for this batch
 * @member {String} batchID
 */
APIResponsesBatchDetails.prototype['batchID'] = undefined;

/**
 * The name of the batch
 * @member {String} batchName
 */
APIResponsesBatchDetails.prototype['batchName'] = undefined;

/**
 * The current payment balance held within the batch
 * @member {Number} totalAmountInBatch
 */
APIResponsesBatchDetails.prototype['totalAmountInBatch'] = undefined;

/**
 * The status of the batch
 * @member {String} status
 */
APIResponsesBatchDetails.prototype['status'] = undefined;

/**
 * @member {Array.<module:model/APIResponsesBatchTenancy>} tenancies
 */
APIResponsesBatchDetails.prototype['tenancies'] = undefined;






export default APIResponsesBatchDetails;

