/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APIResponsesErrors from './APIResponsesErrors';

/**
 * The APIResponsesErrorList model module.
 * @module model/APIResponsesErrorList
 * @version 1.2.2
 */
class APIResponsesErrorList {
    /**
     * Constructs a new <code>APIResponsesErrorList</code>.
     * @alias module:model/APIResponsesErrorList
     */
    constructor() { 
        
        APIResponsesErrorList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesErrorList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesErrorList} obj Optional instance to populate.
     * @return {module:model/APIResponsesErrorList} The populated <code>APIResponsesErrorList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesErrorList();

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [APIResponsesErrors]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/APIResponsesErrors>} errors
 */
APIResponsesErrorList.prototype['errors'] = undefined;






export default APIResponsesErrorList;

