/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesPaymentDetails model module.
 * @module model/APIResponsesPaymentDetails
 * @version 1.2.2
 */
class APIResponsesPaymentDetails {
    /**
     * Constructs a new <code>APIResponsesPaymentDetails</code>.
     * Summary of payment details
     * @alias module:model/APIResponsesPaymentDetails
     */
    constructor() { 
        
        APIResponsesPaymentDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesPaymentDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesPaymentDetails} obj Optional instance to populate.
     * @return {module:model/APIResponsesPaymentDetails} The populated <code>APIResponsesPaymentDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesPaymentDetails();

            if (data.hasOwnProperty('paymentDetailsID')) {
                obj['paymentDetailsID'] = ApiClient.convertToType(data['paymentDetailsID'], 'String');
            }
            if (data.hasOwnProperty('beneficiaryName')) {
                obj['beneficiaryName'] = ApiClient.convertToType(data['beneficiaryName'], 'String');
            }
            if (data.hasOwnProperty('bankAccountNumber')) {
                obj['bankAccountNumber'] = ApiClient.convertToType(data['bankAccountNumber'], 'String');
            }
            if (data.hasOwnProperty('bankSortCode')) {
                obj['bankSortCode'] = ApiClient.convertToType(data['bankSortCode'], 'String');
            }
            if (data.hasOwnProperty('isDefaultPayment')) {
                obj['isDefaultPayment'] = ApiClient.convertToType(data['isDefaultPayment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The unique ID of the payment details record
 * @member {String} paymentDetailsID
 */
APIResponsesPaymentDetails.prototype['paymentDetailsID'] = undefined;

/**
 * The name linked to the bank account
 * @member {String} beneficiaryName
 */
APIResponsesPaymentDetails.prototype['beneficiaryName'] = undefined;

/**
 * The bank account number the deposit should be paid into
 * @member {String} bankAccountNumber
 */
APIResponsesPaymentDetails.prototype['bankAccountNumber'] = undefined;

/**
 * The sort code of the account the deposit should be paid into
 * @member {String} bankSortCode
 */
APIResponsesPaymentDetails.prototype['bankSortCode'] = undefined;

/**
 * Whether this is the default payment method or not, will be either \"true\" or \"false\"
 * @member {String} isDefaultPayment
 */
APIResponsesPaymentDetails.prototype['isDefaultPayment'] = undefined;






export default APIResponsesPaymentDetails;

