/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesTenancy model module.
 * @module model/APIResponsesTenancy
 * @version 1.2.2
 */
class APIResponsesTenancy {
    /**
     * Constructs a new <code>APIResponsesTenancy</code>.
     * Details of a newly registered tenancy deposit
     * @alias module:model/APIResponsesTenancy
     */
    constructor() { 
        
        APIResponsesTenancy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesTenancy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesTenancy} obj Optional instance to populate.
     * @return {module:model/APIResponsesTenancy} The populated <code>APIResponsesTenancy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesTenancy();

            if (data.hasOwnProperty('tenancyID')) {
                obj['tenancyID'] = ApiClient.convertToType(data['tenancyID'], 'String');
            }
            if (data.hasOwnProperty('protectionFee')) {
                obj['protectionFee'] = ApiClient.convertToType(data['protectionFee'], 'Number');
            }
            if (data.hasOwnProperty('landlordID')) {
                obj['landlordID'] = ApiClient.convertToType(data['landlordID'], 'String');
            }
            if (data.hasOwnProperty('propertyID')) {
                obj['propertyID'] = ApiClient.convertToType(data['propertyID'], 'String');
            }
            if (data.hasOwnProperty('depositAmount')) {
                obj['depositAmount'] = ApiClient.convertToType(data['depositAmount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The mydeposits unique tenancy identifier
 * @member {String} tenancyID
 */
APIResponsesTenancy.prototype['tenancyID'] = undefined;

/**
 * Any outstanding fee needing to be paid before the deposit is protected
 * @member {Number} protectionFee
 */
APIResponsesTenancy.prototype['protectionFee'] = undefined;

/**
 * The mydeposits member number of the landlord relating to the tenancy
 * @member {String} landlordID
 */
APIResponsesTenancy.prototype['landlordID'] = undefined;

/**
 * The mydeposits ID of the property that this tenancy is registered against
 * @member {String} propertyID
 */
APIResponsesTenancy.prototype['propertyID'] = undefined;

/**
 * The value of the protected deposit
 * @member {Number} depositAmount
 */
APIResponsesTenancy.prototype['depositAmount'] = undefined;






export default APIResponsesTenancy;

