/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesUnprotect model module.
 * @module model/APIResponsesUnprotect
 * @version 1.2.2
 */
class APIResponsesUnprotect {
    /**
     * Constructs a new <code>APIResponsesUnprotect</code>.
     * @alias module:model/APIResponsesUnprotect
     */
    constructor() { 
        
        APIResponsesUnprotect.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesUnprotect</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesUnprotect} obj Optional instance to populate.
     * @return {module:model/APIResponsesUnprotect} The populated <code>APIResponsesUnprotect</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesUnprotect();

            if (data.hasOwnProperty('tenancyID')) {
                obj['tenancyID'] = ApiClient.convertToType(data['tenancyID'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('dateUnprotected')) {
                obj['dateUnprotected'] = ApiClient.convertToType(data['dateUnprotected'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The tenancy ID of the deposit you are unprotecting
 * @member {String} tenancyID
 */
APIResponsesUnprotect.prototype['tenancyID'] = undefined;

/**
 * Will be either \"Awaiting tenant response\" for release initiation or countering, or \"Deposit released\"  for accepting a release request.
 * @member {String} status
 */
APIResponsesUnprotect.prototype['status'] = undefined;

/**
 * The date of the deposit unprotection if no deductions were requested, otherwise todays date
 * @member {String} dateUnprotected
 */
APIResponsesUnprotect.prototype['dateUnprotected'] = undefined;






export default APIResponsesUnprotect;

