/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesProperty model module.
 * @module model/APIResponsesProperty
 * @version 1.2.2
 */
class APIResponsesProperty {
    /**
     * Constructs a new <code>APIResponsesProperty</code>.
     * Property response object
     * @alias module:model/APIResponsesProperty
     */
    constructor() { 
        
        APIResponsesProperty.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesProperty</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesProperty} obj Optional instance to populate.
     * @return {module:model/APIResponsesProperty} The populated <code>APIResponsesProperty</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesProperty();

            if (data.hasOwnProperty('propertyID')) {
                obj['propertyID'] = ApiClient.convertToType(data['propertyID'], 'String');
            }
            if (data.hasOwnProperty('propertyReference')) {
                obj['propertyReference'] = ApiClient.convertToType(data['propertyReference'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The mydeposits property ID
 * @member {String} propertyID
 */
APIResponsesProperty.prototype['propertyID'] = undefined;

/**
 * Your unique third party reference, if we have been given one
 * @member {String} propertyReference
 */
APIResponsesProperty.prototype['propertyReference'] = undefined;






export default APIResponsesProperty;

