/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LocalAuthorityRegion from './LocalAuthorityRegion';
import PropertyType from './PropertyType';

/**
 * The APIResponsesPropertyDetails model module.
 * @module model/APIResponsesPropertyDetails
 * @version 1.2.2
 */
class APIResponsesPropertyDetails {
    /**
     * Constructs a new <code>APIResponsesPropertyDetails</code>.
     * Details of a given property
     * @alias module:model/APIResponsesPropertyDetails
     */
    constructor() { 
        
        APIResponsesPropertyDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesPropertyDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesPropertyDetails} obj Optional instance to populate.
     * @return {module:model/APIResponsesPropertyDetails} The populated <code>APIResponsesPropertyDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesPropertyDetails();

            if (data.hasOwnProperty('propertyID')) {
                obj['propertyID'] = ApiClient.convertToType(data['propertyID'], 'String');
            }
            if (data.hasOwnProperty('thirdPartyReference')) {
                obj['thirdPartyReference'] = ApiClient.convertToType(data['thirdPartyReference'], 'String');
            }
            if (data.hasOwnProperty('addressLine1')) {
                obj['addressLine1'] = ApiClient.convertToType(data['addressLine1'], 'String');
            }
            if (data.hasOwnProperty('addressLine2')) {
                obj['addressLine2'] = ApiClient.convertToType(data['addressLine2'], 'String');
            }
            if (data.hasOwnProperty('addressLine3')) {
                obj['addressLine3'] = ApiClient.convertToType(data['addressLine3'], 'String');
            }
            if (data.hasOwnProperty('addressLine4')) {
                obj['addressLine4'] = ApiClient.convertToType(data['addressLine4'], 'String');
            }
            if (data.hasOwnProperty('postcode')) {
                obj['postcode'] = ApiClient.convertToType(data['postcode'], 'String');
            }
            if (data.hasOwnProperty('propertyType')) {
                obj['propertyType'] = PropertyType.constructFromObject(data['propertyType']);
            }
            if (data.hasOwnProperty('localAuthority')) {
                obj['localAuthority'] = LocalAuthorityRegion.constructFromObject(data['localAuthority']);
            }
            if (data.hasOwnProperty('landlordID')) {
                obj['landlordID'] = ApiClient.convertToType(data['landlordID'], 'String');
            }
            if (data.hasOwnProperty('branchID')) {
                obj['branchID'] = ApiClient.convertToType(data['branchID'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} propertyID
 */
APIResponsesPropertyDetails.prototype['propertyID'] = undefined;

/**
 * @member {String} thirdPartyReference
 */
APIResponsesPropertyDetails.prototype['thirdPartyReference'] = undefined;

/**
 * @member {String} addressLine1
 */
APIResponsesPropertyDetails.prototype['addressLine1'] = undefined;

/**
 * @member {String} addressLine2
 */
APIResponsesPropertyDetails.prototype['addressLine2'] = undefined;

/**
 * @member {String} addressLine3
 */
APIResponsesPropertyDetails.prototype['addressLine3'] = undefined;

/**
 * @member {String} addressLine4
 */
APIResponsesPropertyDetails.prototype['addressLine4'] = undefined;

/**
 * @member {String} postcode
 */
APIResponsesPropertyDetails.prototype['postcode'] = undefined;

/**
 * @member {module:model/PropertyType} propertyType
 */
APIResponsesPropertyDetails.prototype['propertyType'] = undefined;

/**
 * @member {module:model/LocalAuthorityRegion} localAuthority
 */
APIResponsesPropertyDetails.prototype['localAuthority'] = undefined;

/**
 * @member {String} landlordID
 */
APIResponsesPropertyDetails.prototype['landlordID'] = undefined;

/**
 * @member {String} branchID
 */
APIResponsesPropertyDetails.prototype['branchID'] = undefined;






export default APIResponsesPropertyDetails;

