/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesDefaultPayment model module.
 * @module model/APIResponsesDefaultPayment
 * @version 1.2.2
 */
class APIResponsesDefaultPayment {
    /**
     * Constructs a new <code>APIResponsesDefaultPayment</code>.
     * Details of the newly set default payment details
     * @alias module:model/APIResponsesDefaultPayment
     */
    constructor() { 
        
        APIResponsesDefaultPayment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesDefaultPayment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesDefaultPayment} obj Optional instance to populate.
     * @return {module:model/APIResponsesDefaultPayment} The populated <code>APIResponsesDefaultPayment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesDefaultPayment();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('nextReleaseDate')) {
                obj['nextReleaseDate'] = ApiClient.convertToType(data['nextReleaseDate'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Information message - \"By changing your default bank account you will not be able to release any deposits for 7 calendar days\"
 * @member {String} status
 */
APIResponsesDefaultPayment.prototype['status'] = undefined;

/**
 * Releases cannot be created or updated for 7 days following the changing of default payment details (dd/mm/yyyy)
 * @member {String} nextReleaseDate
 */
APIResponsesDefaultPayment.prototype['nextReleaseDate'] = undefined;






export default APIResponsesDefaultPayment;

