/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesLandlord model module.
 * @module model/APIResponsesLandlord
 * @version 1.2.2
 */
class APIResponsesLandlord {
    /**
     * Constructs a new <code>APIResponsesLandlord</code>.
     * @alias module:model/APIResponsesLandlord
     */
    constructor() { 
        
        APIResponsesLandlord.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesLandlord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesLandlord} obj Optional instance to populate.
     * @return {module:model/APIResponsesLandlord} The populated <code>APIResponsesLandlord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesLandlord();

            if (data.hasOwnProperty('landlordID')) {
                obj['landlordID'] = ApiClient.convertToType(data['landlordID'], 'String');
            }
            if (data.hasOwnProperty('landlordReference')) {
                obj['landlordReference'] = ApiClient.convertToType(data['landlordReference'], 'String');
            }
        }
        return obj;
    }


}

/**
 * mydeposits landlord ID of the new landlord
 * @member {String} landlordID
 */
APIResponsesLandlord.prototype['landlordID'] = undefined;

/**
 * Your unique third party reference, if we have been given one
 * @member {String} landlordReference
 */
APIResponsesLandlord.prototype['landlordReference'] = undefined;






export default APIResponsesLandlord;

