/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Country from './Country';
import Title from './Title';

/**
 * The APIResponsesInterestedPartyDetails model module.
 * @module model/APIResponsesInterestedPartyDetails
 * @version 1.2.2
 */
class APIResponsesInterestedPartyDetails {
    /**
     * Constructs a new <code>APIResponsesInterestedPartyDetails</code>.
     * @alias module:model/APIResponsesInterestedPartyDetails
     */
    constructor() { 
        
        APIResponsesInterestedPartyDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesInterestedPartyDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesInterestedPartyDetails} obj Optional instance to populate.
     * @return {module:model/APIResponsesInterestedPartyDetails} The populated <code>APIResponsesInterestedPartyDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesInterestedPartyDetails();

            if (data.hasOwnProperty('interestedPartyID')) {
                obj['interestedPartyID'] = ApiClient.convertToType(data['interestedPartyID'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = Title.constructFromObject(data['title']);
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('addressLine1')) {
                obj['addressLine1'] = ApiClient.convertToType(data['addressLine1'], 'String');
            }
            if (data.hasOwnProperty('addressLine2')) {
                obj['addressLine2'] = ApiClient.convertToType(data['addressLine2'], 'String');
            }
            if (data.hasOwnProperty('addressLine3')) {
                obj['addressLine3'] = ApiClient.convertToType(data['addressLine3'], 'String');
            }
            if (data.hasOwnProperty('addressLine4')) {
                obj['addressLine4'] = ApiClient.convertToType(data['addressLine4'], 'String');
            }
            if (data.hasOwnProperty('postcode')) {
                obj['postcode'] = ApiClient.convertToType(data['postcode'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = Country.constructFromObject(data['countryCode']);
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('mobileTelephone')) {
                obj['mobileTelephone'] = ApiClient.convertToType(data['mobileTelephone'], 'String');
            }
            if (data.hasOwnProperty('workTelephone')) {
                obj['workTelephone'] = ApiClient.convertToType(data['workTelephone'], 'String');
            }
            if (data.hasOwnProperty('homeTelephone')) {
                obj['homeTelephone'] = ApiClient.convertToType(data['homeTelephone'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} interestedPartyID
 */
APIResponsesInterestedPartyDetails.prototype['interestedPartyID'] = undefined;

/**
 * @member {module:model/Title} title
 */
APIResponsesInterestedPartyDetails.prototype['title'] = undefined;

/**
 * @member {String} firstName
 */
APIResponsesInterestedPartyDetails.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
APIResponsesInterestedPartyDetails.prototype['lastName'] = undefined;

/**
 * @member {String} companyName
 */
APIResponsesInterestedPartyDetails.prototype['companyName'] = undefined;

/**
 * @member {String} addressLine1
 */
APIResponsesInterestedPartyDetails.prototype['addressLine1'] = undefined;

/**
 * @member {String} addressLine2
 */
APIResponsesInterestedPartyDetails.prototype['addressLine2'] = undefined;

/**
 * @member {String} addressLine3
 */
APIResponsesInterestedPartyDetails.prototype['addressLine3'] = undefined;

/**
 * @member {String} addressLine4
 */
APIResponsesInterestedPartyDetails.prototype['addressLine4'] = undefined;

/**
 * @member {String} postcode
 */
APIResponsesInterestedPartyDetails.prototype['postcode'] = undefined;

/**
 * @member {module:model/Country} countryCode
 */
APIResponsesInterestedPartyDetails.prototype['countryCode'] = undefined;

/**
 * @member {String} emailAddress
 */
APIResponsesInterestedPartyDetails.prototype['emailAddress'] = undefined;

/**
 * @member {String} mobileTelephone
 */
APIResponsesInterestedPartyDetails.prototype['mobileTelephone'] = undefined;

/**
 * @member {String} workTelephone
 */
APIResponsesInterestedPartyDetails.prototype['workTelephone'] = undefined;

/**
 * @member {String} homeTelephone
 */
APIResponsesInterestedPartyDetails.prototype['homeTelephone'] = undefined;






export default APIResponsesInterestedPartyDetails;

