/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesOTP model module.
 * @module model/APIResponsesOTP
 * @version 1.2.2
 */
class APIResponsesOTP {
    /**
     * Constructs a new <code>APIResponsesOTP</code>.
     * @alias module:model/APIResponsesOTP
     */
    constructor() { 
        
        APIResponsesOTP.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesOTP</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesOTP} obj Optional instance to populate.
     * @return {module:model/APIResponsesOTP} The populated <code>APIResponsesOTP</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesOTP();

            if (data.hasOwnProperty('communicationMethod')) {
                obj['communicationMethod'] = ApiClient.convertToType(data['communicationMethod'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Will notify you whether the OTP was sent via email or SMS. Possible values are \"EMAIL\" or \"SMS\"
 * @member {String} communicationMethod
 */
APIResponsesOTP.prototype['communicationMethod'] = undefined;






export default APIResponsesOTP;

