/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APIResponsesInterestedPartyDetails from './APIResponsesInterestedPartyDetails';
import APIResponsesJointTenant from './APIResponsesJointTenant';
import APIResponsesLandlord from './APIResponsesLandlord';
import APIResponsesLeadTenant from './APIResponsesLeadTenant';
import APIResponsesProperty from './APIResponsesProperty';
import TenancyStatus from './TenancyStatus';

/**
 * The APIResponsesTenancyDetails model module.
 * @module model/APIResponsesTenancyDetails
 * @version 1.2.2
 */
class APIResponsesTenancyDetails {
    /**
     * Constructs a new <code>APIResponsesTenancyDetails</code>.
     * Details of a given tenancy ID
     * @alias module:model/APIResponsesTenancyDetails
     */
    constructor() { 
        
        APIResponsesTenancyDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesTenancyDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesTenancyDetails} obj Optional instance to populate.
     * @return {module:model/APIResponsesTenancyDetails} The populated <code>APIResponsesTenancyDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesTenancyDetails();

            if (data.hasOwnProperty('tenancyID')) {
                obj['tenancyID'] = ApiClient.convertToType(data['tenancyID'], 'String');
            }
            if (data.hasOwnProperty('depositProtectionNumber')) {
                obj['depositProtectionNumber'] = ApiClient.convertToType(data['depositProtectionNumber'], 'String');
            }
            if (data.hasOwnProperty('thirdPartyReference')) {
                obj['thirdPartyReference'] = ApiClient.convertToType(data['thirdPartyReference'], 'String');
            }
            if (data.hasOwnProperty('tenancyType')) {
                obj['tenancyType'] = ApiClient.convertToType(data['tenancyType'], 'String');
            }
            if (data.hasOwnProperty('depositHolder')) {
                obj['depositHolder'] = ApiClient.convertToType(data['depositHolder'], 'String');
            }
            if (data.hasOwnProperty('depositAmount')) {
                obj['depositAmount'] = ApiClient.convertToType(data['depositAmount'], 'String');
            }
            if (data.hasOwnProperty('protectedAmount')) {
                obj['protectedAmount'] = ApiClient.convertToType(data['protectedAmount'], 'String');
            }
            if (data.hasOwnProperty('dateDepositPaid')) {
                obj['dateDepositPaid'] = ApiClient.convertToType(data['dateDepositPaid'], 'String');
            }
            if (data.hasOwnProperty('tenancyStartDate')) {
                obj['tenancyStartDate'] = ApiClient.convertToType(data['tenancyStartDate'], 'String');
            }
            if (data.hasOwnProperty('tenancyEndDate')) {
                obj['tenancyEndDate'] = ApiClient.convertToType(data['tenancyEndDate'], 'String');
            }
            if (data.hasOwnProperty('annualRentalAmount')) {
                obj['annualRentalAmount'] = ApiClient.convertToType(data['annualRentalAmount'], 'String');
            }
            if (data.hasOwnProperty('landlordRegistrationNumber')) {
                obj['landlordRegistrationNumber'] = ApiClient.convertToType(data['landlordRegistrationNumber'], 'String');
            }
            if (data.hasOwnProperty('landlord')) {
                obj['landlord'] = APIResponsesLandlord.constructFromObject(data['landlord']);
            }
            if (data.hasOwnProperty('property')) {
                obj['property'] = APIResponsesProperty.constructFromObject(data['property']);
            }
            if (data.hasOwnProperty('leadTenant')) {
                obj['leadTenant'] = APIResponsesLeadTenant.constructFromObject(data['leadTenant']);
            }
            if (data.hasOwnProperty('jointTenants')) {
                obj['jointTenants'] = ApiClient.convertToType(data['jointTenants'], [APIResponsesJointTenant]);
            }
            if (data.hasOwnProperty('interestedParty')) {
                obj['interestedParty'] = APIResponsesInterestedPartyDetails.constructFromObject(data['interestedParty']);
            }
            if (data.hasOwnProperty('branchID')) {
                obj['branchID'] = ApiClient.convertToType(data['branchID'], 'String');
            }
            if (data.hasOwnProperty('currentStatus')) {
                obj['currentStatus'] = TenancyStatus.constructFromObject(data['currentStatus']);
            }
        }
        return obj;
    }


}

/**
 * Our unique reference for this tenancy
 * @member {String} tenancyID
 */
APIResponsesTenancyDetails.prototype['tenancyID'] = undefined;

/**
 * Deposit protection number
 * @member {String} depositProtectionNumber
 */
APIResponsesTenancyDetails.prototype['depositProtectionNumber'] = undefined;

/**
 * Your unique reference for this tenancy, if we have been given one
 * @member {String} thirdPartyReference
 */
APIResponsesTenancyDetails.prototype['thirdPartyReference'] = undefined;

/**
 * The type of tenancy this deposit is against
 * @member {String} tenancyType
 */
APIResponsesTenancyDetails.prototype['tenancyType'] = undefined;

/**
 * Insurance Only - Agent / Landlord
 * @member {String} depositHolder
 */
APIResponsesTenancyDetails.prototype['depositHolder'] = undefined;

/**
 * Stated value of the deposit, up to 2 decimal places
 * @member {String} depositAmount
 */
APIResponsesTenancyDetails.prototype['depositAmount'] = undefined;

/**
 * Value of the protected deposit, up to 2 decimal places
 * @member {String} protectedAmount
 */
APIResponsesTenancyDetails.prototype['protectedAmount'] = undefined;

/**
 * The date the landlord/agent received the deposit (dd/MM/yyyy)
 * @member {String} dateDepositPaid
 */
APIResponsesTenancyDetails.prototype['dateDepositPaid'] = undefined;

/**
 * The date the tenancy started (dd/MM/yyyy)
 * @member {String} tenancyStartDate
 */
APIResponsesTenancyDetails.prototype['tenancyStartDate'] = undefined;

/**
 * The date the tenancy ended (dd/MM/yyyy)
 * @member {String} tenancyEndDate
 */
APIResponsesTenancyDetails.prototype['tenancyEndDate'] = undefined;

/**
 * @member {String} annualRentalAmount
 */
APIResponsesTenancyDetails.prototype['annualRentalAmount'] = undefined;

/**
 * Only needed for Scotland Custodial, landlord registration number for local authority that the property resides in
 * @member {String} landlordRegistrationNumber
 */
APIResponsesTenancyDetails.prototype['landlordRegistrationNumber'] = undefined;

/**
 * @member {module:model/APIResponsesLandlord} landlord
 */
APIResponsesTenancyDetails.prototype['landlord'] = undefined;

/**
 * @member {module:model/APIResponsesProperty} property
 */
APIResponsesTenancyDetails.prototype['property'] = undefined;

/**
 * @member {module:model/APIResponsesLeadTenant} leadTenant
 */
APIResponsesTenancyDetails.prototype['leadTenant'] = undefined;

/**
 * @member {Array.<module:model/APIResponsesJointTenant>} jointTenants
 */
APIResponsesTenancyDetails.prototype['jointTenants'] = undefined;

/**
 * @member {module:model/APIResponsesInterestedPartyDetails} interestedParty
 */
APIResponsesTenancyDetails.prototype['interestedParty'] = undefined;

/**
 * @member {String} branchID
 */
APIResponsesTenancyDetails.prototype['branchID'] = undefined;

/**
 * @member {module:model/TenancyStatus} currentStatus
 */
APIResponsesTenancyDetails.prototype['currentStatus'] = undefined;






export default APIResponsesTenancyDetails;

