/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesCheckout model module.
 * @module model/APIResponsesCheckout
 * @version 1.2.2
 */
class APIResponsesCheckout {
    /**
     * Constructs a new <code>APIResponsesCheckout</code>.
     * @alias module:model/APIResponsesCheckout
     */
    constructor() { 
        
        APIResponsesCheckout.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesCheckout</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesCheckout} obj Optional instance to populate.
     * @return {module:model/APIResponsesCheckout} The populated <code>APIResponsesCheckout</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesCheckout();

            if (data.hasOwnProperty('tenancyID')) {
                obj['tenancyID'] = ApiClient.convertToType(data['tenancyID'], 'String');
            }
            if (data.hasOwnProperty('depositAmount')) {
                obj['depositAmount'] = ApiClient.convertToType(data['depositAmount'], 'Number');
            }
            if (data.hasOwnProperty('paymentReference')) {
                obj['paymentReference'] = ApiClient.convertToType(data['paymentReference'], 'String');
            }
            if (data.hasOwnProperty('protectionFee')) {
                obj['protectionFee'] = ApiClient.convertToType(data['protectionFee'], 'Number');
            }
            if (data.hasOwnProperty('bankAccountNumber')) {
                obj['bankAccountNumber'] = ApiClient.convertToType(data['bankAccountNumber'], 'String');
            }
            if (data.hasOwnProperty('bankSortCode')) {
                obj['bankSortCode'] = ApiClient.convertToType(data['bankSortCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The ID of the tenancy being checked out
 * @member {String} tenancyID
 */
APIResponsesCheckout.prototype['tenancyID'] = undefined;

/**
 * The monetary value of the tenancy that you need to send to us via bank transfer
 * @member {Number} depositAmount
 */
APIResponsesCheckout.prototype['depositAmount'] = undefined;

/**
 * The unique payment reference to use when submitting a bank transfer to us to pay for the tenancy
 * @member {String} paymentReference
 */
APIResponsesCheckout.prototype['paymentReference'] = undefined;

/**
 * Any applicable fee charged for this protection
 * @member {Number} protectionFee
 */
APIResponsesCheckout.prototype['protectionFee'] = undefined;

/**
 * The mydeposits bank account number to transfer the payment into.
 * @member {String} bankAccountNumber
 */
APIResponsesCheckout.prototype['bankAccountNumber'] = undefined;

/**
 * The mydeposits bank sort code to transfer the payment into.
 * @member {String} bankSortCode
 */
APIResponsesCheckout.prototype['bankSortCode'] = undefined;






export default APIResponsesCheckout;

