/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TenancyStatus from './TenancyStatus';

/**
 * The APIResponsesProtection model module.
 * @module model/APIResponsesProtection
 * @version 1.2.2
 */
class APIResponsesProtection {
    /**
     * Constructs a new <code>APIResponsesProtection</code>.
     * Summary of tenancy details
     * @alias module:model/APIResponsesProtection
     */
    constructor() { 
        
        APIResponsesProtection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesProtection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesProtection} obj Optional instance to populate.
     * @return {module:model/APIResponsesProtection} The populated <code>APIResponsesProtection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesProtection();

            if (data.hasOwnProperty('branchID')) {
                obj['branchID'] = ApiClient.convertToType(data['branchID'], 'String');
            }
            if (data.hasOwnProperty('tenancyID')) {
                obj['tenancyID'] = ApiClient.convertToType(data['tenancyID'], 'String');
            }
            if (data.hasOwnProperty('depositProtectionNumber')) {
                obj['depositProtectionNumber'] = ApiClient.convertToType(data['depositProtectionNumber'], 'String');
            }
            if (data.hasOwnProperty('tenancyStartDate')) {
                obj['tenancyStartDate'] = ApiClient.convertToType(data['tenancyStartDate'], 'String');
            }
            if (data.hasOwnProperty('tenancyEndDate')) {
                obj['tenancyEndDate'] = ApiClient.convertToType(data['tenancyEndDate'], 'String');
            }
            if (data.hasOwnProperty('depositAmount')) {
                obj['depositAmount'] = ApiClient.convertToType(data['depositAmount'], 'String');
            }
            if (data.hasOwnProperty('protectedAmount')) {
                obj['protectedAmount'] = ApiClient.convertToType(data['protectedAmount'], 'String');
            }
            if (data.hasOwnProperty('currentStatus')) {
                obj['currentStatus'] = TenancyStatus.constructFromObject(data['currentStatus']);
            }
        }
        return obj;
    }


}

/**
 * The branch that the deposit is linked to
 * @member {String} branchID
 */
APIResponsesProtection.prototype['branchID'] = undefined;

/**
 * The mydeposits unique ID for this tenancy
 * @member {String} tenancyID
 */
APIResponsesProtection.prototype['tenancyID'] = undefined;

/**
 * The certificate number for this tenancy
 * @member {String} depositProtectionNumber
 */
APIResponsesProtection.prototype['depositProtectionNumber'] = undefined;

/**
 * The start date of the tenancy
 * @member {String} tenancyStartDate
 */
APIResponsesProtection.prototype['tenancyStartDate'] = undefined;

/**
 * The end date of the tenancy
 * @member {String} tenancyEndDate
 */
APIResponsesProtection.prototype['tenancyEndDate'] = undefined;

/**
 * The deposits amount
 * @member {String} depositAmount
 */
APIResponsesProtection.prototype['depositAmount'] = undefined;

/**
 * The amount of the deposit to be protected
 * @member {String} protectedAmount
 */
APIResponsesProtection.prototype['protectedAmount'] = undefined;

/**
 * @member {module:model/TenancyStatus} currentStatus
 */
APIResponsesProtection.prototype['currentStatus'] = undefined;






export default APIResponsesProtection;

