/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesBranchDetails model module.
 * @module model/APIResponsesBranchDetails
 * @version 1.2.2
 */
class APIResponsesBranchDetails {
    /**
     * Constructs a new <code>APIResponsesBranchDetails</code>.
     * Summary of branch details
     * @alias module:model/APIResponsesBranchDetails
     */
    constructor() { 
        
        APIResponsesBranchDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesBranchDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesBranchDetails} obj Optional instance to populate.
     * @return {module:model/APIResponsesBranchDetails} The populated <code>APIResponsesBranchDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesBranchDetails();

            if (data.hasOwnProperty('branchID')) {
                obj['branchID'] = ApiClient.convertToType(data['branchID'], 'String');
            }
            if (data.hasOwnProperty('parentBranchID')) {
                obj['parentBranchID'] = ApiClient.convertToType(data['parentBranchID'], 'String');
            }
            if (data.hasOwnProperty('thirdPartyReference')) {
                obj['thirdPartyReference'] = ApiClient.convertToType(data['thirdPartyReference'], 'String');
            }
            if (data.hasOwnProperty('branchName')) {
                obj['branchName'] = ApiClient.convertToType(data['branchName'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('addressLine1')) {
                obj['addressLine1'] = ApiClient.convertToType(data['addressLine1'], 'String');
            }
            if (data.hasOwnProperty('addressLine2')) {
                obj['addressLine2'] = ApiClient.convertToType(data['addressLine2'], 'String');
            }
            if (data.hasOwnProperty('addressLine3')) {
                obj['addressLine3'] = ApiClient.convertToType(data['addressLine3'], 'String');
            }
            if (data.hasOwnProperty('addressLine4')) {
                obj['addressLine4'] = ApiClient.convertToType(data['addressLine4'], 'String');
            }
            if (data.hasOwnProperty('postcode')) {
                obj['postcode'] = ApiClient.convertToType(data['postcode'], 'String');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('mobileTelephone')) {
                obj['mobileTelephone'] = ApiClient.convertToType(data['mobileTelephone'], 'String');
            }
            if (data.hasOwnProperty('branchTelephone')) {
                obj['branchTelephone'] = ApiClient.convertToType(data['branchTelephone'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The unique ID of the branch record
 * @member {String} branchID
 */
APIResponsesBranchDetails.prototype['branchID'] = undefined;

/**
 * The branch ID (if any) of the parent branch for this record
 * @member {String} parentBranchID
 */
APIResponsesBranchDetails.prototype['parentBranchID'] = undefined;

/**
 * @member {String} thirdPartyReference
 */
APIResponsesBranchDetails.prototype['thirdPartyReference'] = undefined;

/**
 * @member {String} branchName
 */
APIResponsesBranchDetails.prototype['branchName'] = undefined;

/**
 * Required field for Insurance only
 * @member {module:model/APIResponsesBranchDetails.TitleEnum} title
 */
APIResponsesBranchDetails.prototype['title'] = undefined;

/**
 * Required for Insurance only. 50 characters or less
 * @member {String} firstName
 */
APIResponsesBranchDetails.prototype['firstName'] = undefined;

/**
 * Required for Insurance only. 50 characters or less
 * @member {String} lastName
 */
APIResponsesBranchDetails.prototype['lastName'] = undefined;

/**
 * @member {String} addressLine1
 */
APIResponsesBranchDetails.prototype['addressLine1'] = undefined;

/**
 * @member {String} addressLine2
 */
APIResponsesBranchDetails.prototype['addressLine2'] = undefined;

/**
 * @member {String} addressLine3
 */
APIResponsesBranchDetails.prototype['addressLine3'] = undefined;

/**
 * @member {String} addressLine4
 */
APIResponsesBranchDetails.prototype['addressLine4'] = undefined;

/**
 * @member {String} postcode
 */
APIResponsesBranchDetails.prototype['postcode'] = undefined;

/**
 * @member {String} emailAddress
 */
APIResponsesBranchDetails.prototype['emailAddress'] = undefined;

/**
 * @member {String} mobileTelephone
 */
APIResponsesBranchDetails.prototype['mobileTelephone'] = undefined;

/**
 * @member {String} branchTelephone
 */
APIResponsesBranchDetails.prototype['branchTelephone'] = undefined;





/**
 * Allowed values for the <code>title</code> property.
 * @enum {String}
 * @readonly
 */
APIResponsesBranchDetails['TitleEnum'] = {

    /**
     * value: "Mr"
     * @const
     */
    "Mr": "Mr",

    /**
     * value: "Mrs"
     * @const
     */
    "Mrs": "Mrs",

    /**
     * value: "Miss"
     * @const
     */
    "Miss": "Miss",

    /**
     * value: "Ms"
     * @const
     */
    "Ms": "Ms",

    /**
     * value: "Dr"
     * @const
     */
    "Dr": "Dr",

    /**
     * value: "Lady"
     * @const
     */
    "Lady": "Lady",

    /**
     * value: "Lord"
     * @const
     */
    "Lord": "Lord",

    /**
     * value: "Professor"
     * @const
     */
    "Professor": "Professor",

    /**
     * value: "Sir"
     * @const
     */
    "Sir": "Sir"
};



export default APIResponsesBranchDetails;

