/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesPaymentDetail model module.
 * @module model/APIResponsesPaymentDetail
 * @version 1.2.2
 */
class APIResponsesPaymentDetail {
    /**
     * Constructs a new <code>APIResponsesPaymentDetail</code>.
     * ID of the newly added payment detail
     * @alias module:model/APIResponsesPaymentDetail
     */
    constructor() { 
        
        APIResponsesPaymentDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesPaymentDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesPaymentDetail} obj Optional instance to populate.
     * @return {module:model/APIResponsesPaymentDetail} The populated <code>APIResponsesPaymentDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesPaymentDetail();

            if (data.hasOwnProperty('bacsPaymentDetailsID')) {
                obj['bacsPaymentDetailsID'] = ApiClient.convertToType(data['bacsPaymentDetailsID'], 'String');
            }
            if (data.hasOwnProperty('isDefaultPayment')) {
                obj['isDefaultPayment'] = ApiClient.convertToType(data['isDefaultPayment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The unique ID of the payment details record
 * @member {String} bacsPaymentDetailsID
 */
APIResponsesPaymentDetail.prototype['bacsPaymentDetailsID'] = undefined;

/**
 * Whether this is the default payment method or not, will be either \"true\" or \"false\"
 * @member {String} isDefaultPayment
 */
APIResponsesPaymentDetail.prototype['isDefaultPayment'] = undefined;






export default APIResponsesPaymentDetail;

