/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APIResponsesPaymentDetails from './APIResponsesPaymentDetails';

/**
 * The APIResponsesPaymentDetailsList model module.
 * @module model/APIResponsesPaymentDetailsList
 * @version 1.2.2
 */
class APIResponsesPaymentDetailsList {
    /**
     * Constructs a new <code>APIResponsesPaymentDetailsList</code>.
     * @alias module:model/APIResponsesPaymentDetailsList
     */
    constructor() { 
        
        APIResponsesPaymentDetailsList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesPaymentDetailsList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesPaymentDetailsList} obj Optional instance to populate.
     * @return {module:model/APIResponsesPaymentDetailsList} The populated <code>APIResponsesPaymentDetailsList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesPaymentDetailsList();

            if (data.hasOwnProperty('paymentDetails')) {
                obj['paymentDetails'] = ApiClient.convertToType(data['paymentDetails'], [APIResponsesPaymentDetails]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/APIResponsesPaymentDetails>} paymentDetails
 */
APIResponsesPaymentDetailsList.prototype['paymentDetails'] = undefined;






export default APIResponsesPaymentDetailsList;

