/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIResponsesSchemeRules model module.
 * @module model/APIResponsesSchemeRules
 * @version 1.2.2
 */
class APIResponsesSchemeRules {
    /**
     * Constructs a new <code>APIResponsesSchemeRules</code>.
     * Model for a new member scheme subscription
     * @alias module:model/APIResponsesSchemeRules
     */
    constructor() { 
        
        APIResponsesSchemeRules.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIResponsesSchemeRules</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIResponsesSchemeRules} obj Optional instance to populate.
     * @return {module:model/APIResponsesSchemeRules} The populated <code>APIResponsesSchemeRules</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIResponsesSchemeRules();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * URL of the requested Scheme Rules
 * @member {String} url
 */
APIResponsesSchemeRules.prototype['url'] = undefined;






export default APIResponsesSchemeRules;

