/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LocalAuthorityRegion.
* @enum {}
* @readonly
*/
export default class LocalAuthorityRegion {
    
        /**
         * value: "AberdeenCity,"
         * @const
         */
        "AberdeenCity," = "AberdeenCity,";

    
        /**
         * value: "Aberdeenshire,"
         * @const
         */
        "Aberdeenshire," = "Aberdeenshire,";

    
        /**
         * value: "Angus,"
         * @const
         */
        "Angus," = "Angus,";

    
        /**
         * value: "ArgyllAndBute,"
         * @const
         */
        "ArgyllAndBute," = "ArgyllAndBute,";

    
        /**
         * value: "Clackmannanshire,"
         * @const
         */
        "Clackmannanshire," = "Clackmannanshire,";

    
        /**
         * value: "DumfriesAndGalloway,"
         * @const
         */
        "DumfriesAndGalloway," = "DumfriesAndGalloway,";

    
        /**
         * value: "DundeeCity,"
         * @const
         */
        "DundeeCity," = "DundeeCity,";

    
        /**
         * value: "EastAyrshire,"
         * @const
         */
        "EastAyrshire," = "EastAyrshire,";

    
        /**
         * value: "EastDunbartonshire,"
         * @const
         */
        "EastDunbartonshire," = "EastDunbartonshire,";

    
        /**
         * value: "EastLothian,"
         * @const
         */
        "EastLothian," = "EastLothian,";

    
        /**
         * value: "EastRenfrewshire,"
         * @const
         */
        "EastRenfrewshire," = "EastRenfrewshire,";

    
        /**
         * value: "Edinburgh,"
         * @const
         */
        "Edinburgh," = "Edinburgh,";

    
        /**
         * value: "EileanSiar,"
         * @const
         */
        "EileanSiar," = "EileanSiar,";

    
        /**
         * value: "Falkirk,"
         * @const
         */
        "Falkirk," = "Falkirk,";

    
        /**
         * value: "Fife,"
         * @const
         */
        "Fife," = "Fife,";

    
        /**
         * value: "GlasgowCity,"
         * @const
         */
        "GlasgowCity," = "GlasgowCity,";

    
        /**
         * value: "Highland,"
         * @const
         */
        "Highland," = "Highland,";

    
        /**
         * value: "Inverclyde,"
         * @const
         */
        "Inverclyde," = "Inverclyde,";

    
        /**
         * value: "Midlothian,"
         * @const
         */
        "Midlothian," = "Midlothian,";

    
        /**
         * value: "Moray,"
         * @const
         */
        "Moray," = "Moray,";

    
        /**
         * value: "NorthAyrshire,"
         * @const
         */
        "NorthAyrshire," = "NorthAyrshire,";

    
        /**
         * value: "NorthLanarkshire,"
         * @const
         */
        "NorthLanarkshire," = "NorthLanarkshire,";

    
        /**
         * value: "OrkneyIslands,"
         * @const
         */
        "OrkneyIslands," = "OrkneyIslands,";

    
        /**
         * value: "PerthAndKinross,"
         * @const
         */
        "PerthAndKinross," = "PerthAndKinross,";

    
        /**
         * value: "Renfrewshire,"
         * @const
         */
        "Renfrewshire," = "Renfrewshire,";

    
        /**
         * value: "ScottishBorders,"
         * @const
         */
        "ScottishBorders," = "ScottishBorders,";

    
        /**
         * value: "ShetlandIslands,"
         * @const
         */
        "ShetlandIslands," = "ShetlandIslands,";

    
        /**
         * value: "SouthAyrshire,"
         * @const
         */
        "SouthAyrshire," = "SouthAyrshire,";

    
        /**
         * value: "SouthLanarkshire,"
         * @const
         */
        "SouthLanarkshire," = "SouthLanarkshire,";

    
        /**
         * value: "Stirling,"
         * @const
         */
        "Stirling," = "Stirling,";

    
        /**
         * value: "WestDunbartonshire,"
         * @const
         */
        "WestDunbartonshire," = "WestDunbartonshire,";

    
        /**
         * value: "WestLothian"
         * @const
         */
        "WestLothian" = "WestLothian";

    

    /**
    * Returns a <code>LocalAuthorityRegion</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LocalAuthorityRegion} The enum <code>LocalAuthorityRegion</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

