/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PropertyType.
* @enum {}
* @readonly
*/
export default class PropertyType {
    
        /**
         * value: "HOUSE"
         * @const
         */
        "HOUSE" = "HOUSE";

    
        /**
         * value: "FLAT"
         * @const
         */
        "FLAT" = "FLAT";

    
        /**
         * value: "MAISONETTE"
         * @const
         */
        "MAISONETTE" = "MAISONETTE";

    
        /**
         * value: "ROOM"
         * @const
         */
        "ROOM" = "ROOM";

    

    /**
    * Returns a <code>PropertyType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PropertyType} The enum <code>PropertyType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

