/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TenancyStatus.
* @enum {}
* @readonly
*/
export default class TenancyStatus {
    
        /**
         * value: "registered"
         * @const
         */
        "registered" = "registered";

    
        /**
         * value: "awaiting payment"
         * @const
         */
        "awaiting payment" = "awaiting payment";

    
        /**
         * value: "protected awaiting payment (insurance only)"
         * @const
         */
        "protected awaiting payment (insurance only)" = "protected awaiting payment (insurance only)";

    
        /**
         * value: "protected"
         * @const
         */
        "protected" = "protected";

    
        /**
         * value: "release initiated (custodial only)"
         * @const
         */
        "release initiated (custodial only)" = "release initiated (custodial only)";

    
        /**
         * value: "unprotected"
         * @const
         */
        "unprotected" = "unprotected";

    
        /**
         * value: "release in dispute"
         * @const
         */
        "release in dispute" = "release in dispute";

    
        /**
         * value: "release in court"
         * @const
         */
        "release in court" = "release in court";

    
        /**
         * value: "cancelled"
         * @const
         */
        "cancelled" = "cancelled";

    
        /**
         * value: "closed"
         * @const
         */
        "closed" = "closed";

    
        /**
         * value: "cheque bounced"
         * @const
         */
        "cheque bounced" = "cheque bounced";

    

    /**
    * Returns a <code>TenancyStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TenancyStatus} The enum <code>TenancyStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

