/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TenancyType.
* @enum {}
* @readonly
*/
export default class TenancyType {
    
        /**
         * value: "ASSURED_SHORTHOLD"
         * @const
         */
        "ASSURED_SHORTHOLD" = "ASSURED_SHORTHOLD";

    
        /**
         * value: "NON_ASSURED_SHORTHOLD"
         * @const
         */
        "NON_ASSURED_SHORTHOLD" = "NON_ASSURED_SHORTHOLD";

    
        /**
         * value: "COMPANY_LET"
         * @const
         */
        "COMPANY_LET" = "COMPANY_LET";

    
        /**
         * value: "PRIVATE_RESIDENTIAL"
         * @const
         */
        "PRIVATE_RESIDENTIAL" = "PRIVATE_RESIDENTIAL";

    

    /**
    * Returns a <code>TenancyType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TenancyType} The enum <code>TenancyType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

