/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Title.
* @enum {}
* @readonly
*/
export default class Title {
    
        /**
         * value: "Mr"
         * @const
         */
        "Mr" = "Mr";

    
        /**
         * value: "Mrs"
         * @const
         */
        "Mrs" = "Mrs";

    
        /**
         * value: "Miss"
         * @const
         */
        "Miss" = "Miss";

    
        /**
         * value: "Ms"
         * @const
         */
        "Ms" = "Ms";

    
        /**
         * value: "Dr"
         * @const
         */
        "Dr" = "Dr";

    
        /**
         * value: "Lady"
         * @const
         */
        "Lady" = "Lady";

    
        /**
         * value: "Lord"
         * @const
         */
        "Lord" = "Lord";

    
        /**
         * value: "Professor"
         * @const
         */
        "Professor" = "Professor";

    
        /**
         * value: "Sir"
         * @const
         */
        "Sir" = "Sir";

    
        /**
         * value: "Mx"
         * @const
         */
        "Mx" = "Mx";

    

    /**
    * Returns a <code>Title</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Title} The enum <code>Title</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

