/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import APIModelsProperty from '../model/APIModelsProperty';
import APIResponsesErrorList from '../model/APIResponsesErrorList';
import APIResponsesProperty from '../model/APIResponsesProperty';
import APIResponsesPropertyDetails from '../model/APIResponsesPropertyDetails';

/**
* PropertyServices service.
* @module api/PropertyServicesApi
* @version 1.2.2
*/
export default class PropertyServicesApi {

    /**
    * Constructs a new PropertyServicesApi. 
    * @alias module:api/PropertyServicesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the propertyGet operation.
     * @callback module:api/PropertyServicesApi~propertyGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APIResponsesPropertyDetails} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return all information for this property
     * @param {String} scheme ID of the selected deposit protection Scheme as returned by protectionschemes method.
     * @param {String} region ID of the selected deposit protection Region as returned by protectionregions method.
     * @param {Number} id Property ID
     * @param {module:api/PropertyServicesApi~propertyGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APIResponsesPropertyDetails}
     */
    propertyGet(scheme, region, id, callback) {
      let postBody = null;
      // verify the required parameter 'scheme' is set
      if (scheme === undefined || scheme === null) {
        throw new Error("Missing the required parameter 'scheme' when calling propertyGet");
      }
      // verify the required parameter 'region' is set
      if (region === undefined || region === null) {
        throw new Error("Missing the required parameter 'region' when calling propertyGet");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling propertyGet");
      }

      let pathParams = {
        'scheme': scheme,
        'region': region,
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['mydeposits_accessCode'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = APIResponsesPropertyDetails;
      return this.apiClient.callApi(
        '/v1/{scheme}/{region}/property/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the propertyPost operation.
     * @callback module:api/PropertyServicesApi~propertyPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APIResponsesProperty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new property record within a specified mydeposits member account
     * Allows creation of a new property record within the mydeposits member account for the chosen scheme and region.
     * @param {String} scheme ID of the selected deposit protection Scheme as returned by protectionschemes method.
     * @param {String} region ID of the selected deposit protection Region as returned by protectionregions method.
     * @param {module:model/APIModelsProperty} body Property entity to be created
     * @param {module:api/PropertyServicesApi~propertyPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APIResponsesProperty}
     */
    propertyPost(scheme, region, body, callback) {
      let postBody = body;
      // verify the required parameter 'scheme' is set
      if (scheme === undefined || scheme === null) {
        throw new Error("Missing the required parameter 'scheme' when calling propertyPost");
      }
      // verify the required parameter 'region' is set
      if (region === undefined || region === null) {
        throw new Error("Missing the required parameter 'region' when calling propertyPost");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling propertyPost");
      }

      let pathParams = {
        'scheme': scheme,
        'region': region
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['mydeposits_accessCode'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = APIResponsesProperty;
      return this.apiClient.callApi(
        '/v1/{scheme}/{region}/property', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the propertyPut operation.
     * @callback module:api/PropertyServicesApi~propertyPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APIResponsesProperty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an existing property
     * @param {String} scheme ID of the selected deposit protection Scheme as returned by protectionschemes method.
     * @param {String} region ID of the selected deposit protection Region as returned by protectionregions method.
     * @param {Number} id Property ID
     * @param {module:model/APIModelsProperty} value Models.Property
     * @param {module:api/PropertyServicesApi~propertyPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APIResponsesProperty}
     */
    propertyPut(scheme, region, id, value, callback) {
      let postBody = value;
      // verify the required parameter 'scheme' is set
      if (scheme === undefined || scheme === null) {
        throw new Error("Missing the required parameter 'scheme' when calling propertyPut");
      }
      // verify the required parameter 'region' is set
      if (region === undefined || region === null) {
        throw new Error("Missing the required parameter 'region' when calling propertyPut");
      }
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling propertyPut");
      }
      // verify the required parameter 'value' is set
      if (value === undefined || value === null) {
        throw new Error("Missing the required parameter 'value' when calling propertyPut");
      }

      let pathParams = {
        'scheme': scheme,
        'region': region,
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['mydeposits_accessCode'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = APIResponsesProperty;
      return this.apiClient.callApi(
        '/v1/{scheme}/{region}/property/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
