/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MydepositsDeveloperApi);
  }
}(this, function(expect, MydepositsDeveloperApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('APIResponsesLandlordDetails', function() {
    it('should create an instance of APIResponsesLandlordDetails', function() {
      // uncomment below and update the code to test APIResponsesLandlordDetails
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be.a(MydepositsDeveloperApi.APIResponsesLandlordDetails);
    });

    it('should have the property landlordType (base name: "landlordType")', function() {
      // uncomment below and update the code to test the property landlordType
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property landlordID (base name: "landlordID")', function() {
      // uncomment below and update the code to test the property landlordID
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property thirdPartyReference (base name: "thirdPartyReference")', function() {
      // uncomment below and update the code to test the property thirdPartyReference
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property addressLine1 (base name: "addressLine1")', function() {
      // uncomment below and update the code to test the property addressLine1
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property addressLine2 (base name: "addressLine2")', function() {
      // uncomment below and update the code to test the property addressLine2
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property addressLine3 (base name: "addressLine3")', function() {
      // uncomment below and update the code to test the property addressLine3
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property addressLine4 (base name: "addressLine4")', function() {
      // uncomment below and update the code to test the property addressLine4
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property postcode (base name: "postcode")', function() {
      // uncomment below and update the code to test the property postcode
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "countryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "companyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property companyRegistrationNumber (base name: "companyRegistrationNumber")', function() {
      // uncomment below and update the code to test the property companyRegistrationNumber
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property registeredAddressLine1 (base name: "registeredAddressLine1")', function() {
      // uncomment below and update the code to test the property registeredAddressLine1
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property registeredAddressLine2 (base name: "registeredAddressLine2")', function() {
      // uncomment below and update the code to test the property registeredAddressLine2
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property registeredAddressLine3 (base name: "registeredAddressLine3")', function() {
      // uncomment below and update the code to test the property registeredAddressLine3
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property registeredPostcode (base name: "registeredPostcode")', function() {
      // uncomment below and update the code to test the property registeredPostcode
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property homeTelephone (base name: "homeTelephone")', function() {
      // uncomment below and update the code to test the property homeTelephone
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property mobileTelephone (base name: "mobileTelephone")', function() {
      // uncomment below and update the code to test the property mobileTelephone
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property workTelephone (base name: "workTelephone")', function() {
      // uncomment below and update the code to test the property workTelephone
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property emailAddress (base name: "emailAddress")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

    it('should have the property branchID (base name: "branchID")', function() {
      // uncomment below and update the code to test the property branchID
      //var instane = new MydepositsDeveloperApi.APIResponsesLandlordDetails();
      //expect(instance).to.be();
    });

  });

}));
