/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MydepositsDeveloperApi);
  }
}(this, function(expect, MydepositsDeveloperApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MydepositsDeveloperApi.APIResponsesUnprotect();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('APIResponsesUnprotect', function() {
    it('should create an instance of APIResponsesUnprotect', function() {
      // uncomment below and update the code to test APIResponsesUnprotect
      //var instane = new MydepositsDeveloperApi.APIResponsesUnprotect();
      //expect(instance).to.be.a(MydepositsDeveloperApi.APIResponsesUnprotect);
    });

    it('should have the property tenancyID (base name: "tenancyID")', function() {
      // uncomment below and update the code to test the property tenancyID
      //var instane = new MydepositsDeveloperApi.APIResponsesUnprotect();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new MydepositsDeveloperApi.APIResponsesUnprotect();
      //expect(instance).to.be();
    });

    it('should have the property dateUnprotected (base name: "dateUnprotected")', function() {
      // uncomment below and update the code to test the property dateUnprotected
      //var instane = new MydepositsDeveloperApi.APIResponsesUnprotect();
      //expect(instance).to.be();
    });

  });

}));
