/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import APIModelsBatch from './model/APIModelsBatch';
import APIModelsBatchAddTenancy from './model/APIModelsBatchAddTenancy';
import APIModelsBranch from './model/APIModelsBranch';
import APIModelsCheckout from './model/APIModelsCheckout';
import APIModelsDeductions from './model/APIModelsDeductions';
import APIModelsInterestedParty from './model/APIModelsInterestedParty';
import APIModelsJointTenant from './model/APIModelsJointTenant';
import APIModelsLandlord from './model/APIModelsLandlord';
import APIModelsLandlordMember from './model/APIModelsLandlordMember';
import APIModelsPaymentDetail from './model/APIModelsPaymentDetail';
import APIModelsProperty from './model/APIModelsProperty';
import APIModelsSubscribe from './model/APIModelsSubscribe';
import APIModelsTenancy from './model/APIModelsTenancy';
import APIModelsTenant from './model/APIModelsTenant';
import APIModelsToken from './model/APIModelsToken';
import APIModelsUnprotect from './model/APIModelsUnprotect';
import APIModelsUnprotectAccept from './model/APIModelsUnprotectAccept';
import APIModelsUnprotectionDeductions from './model/APIModelsUnprotectionDeductions';
import APIResponsesBatch from './model/APIResponsesBatch';
import APIResponsesBatchAddTenancy from './model/APIResponsesBatchAddTenancy';
import APIResponsesBatchCheckout from './model/APIResponsesBatchCheckout';
import APIResponsesBatchDetails from './model/APIResponsesBatchDetails';
import APIResponsesBatchList from './model/APIResponsesBatchList';
import APIResponsesBatchTenancy from './model/APIResponsesBatchTenancy';
import APIResponsesBranch from './model/APIResponsesBranch';
import APIResponsesBranchDetails from './model/APIResponsesBranchDetails';
import APIResponsesBranchList from './model/APIResponsesBranchList';
import APIResponsesCheckout from './model/APIResponsesCheckout';
import APIResponsesConvertSPT from './model/APIResponsesConvertSPT';
import APIResponsesDefaultPayment from './model/APIResponsesDefaultPayment';
import APIResponsesErrorList from './model/APIResponsesErrorList';
import APIResponsesErrors from './model/APIResponsesErrors';
import APIResponsesInterestedPartyDetails from './model/APIResponsesInterestedPartyDetails';
import APIResponsesJointTenant from './model/APIResponsesJointTenant';
import APIResponsesLandlord from './model/APIResponsesLandlord';
import APIResponsesLandlordDetails from './model/APIResponsesLandlordDetails';
import APIResponsesLandlordMember from './model/APIResponsesLandlordMember';
import APIResponsesLeadTenant from './model/APIResponsesLeadTenant';
import APIResponsesOTP from './model/APIResponsesOTP';
import APIResponsesPaymentDetail from './model/APIResponsesPaymentDetail';
import APIResponsesPaymentDetails from './model/APIResponsesPaymentDetails';
import APIResponsesPaymentDetailsList from './model/APIResponsesPaymentDetailsList';
import APIResponsesProperty from './model/APIResponsesProperty';
import APIResponsesPropertyDetails from './model/APIResponsesPropertyDetails';
import APIResponsesProtection from './model/APIResponsesProtection';
import APIResponsesProtectionList from './model/APIResponsesProtectionList';
import APIResponsesSchemeRules from './model/APIResponsesSchemeRules';
import APIResponsesTenancy from './model/APIResponsesTenancy';
import APIResponsesTenancyDetails from './model/APIResponsesTenancyDetails';
import APIResponsesToken from './model/APIResponsesToken';
import APIResponsesUnprotect from './model/APIResponsesUnprotect';
import Country from './model/Country';
import DeductionReasons from './model/DeductionReasons';
import InlineResponse200 from './model/InlineResponse200';
import LocalAuthorityRegion from './model/LocalAuthorityRegion';
import PropertyType from './model/PropertyType';
import TenancyStatus from './model/TenancyStatus';
import TenancyType from './model/TenancyType';
import Title from './model/Title';
import AuthenticationServicesApi from './api/AuthenticationServicesApi';
import BatchServicesApi from './api/BatchServicesApi';
import GlobalServicesApi from './api/GlobalServicesApi';
import LandlordServicesApi from './api/LandlordServicesApi';
import MemberAccountServicesApi from './api/MemberAccountServicesApi';
import PropertyServicesApi from './api/PropertyServicesApi';
import TenancyServicesApi from './api/TenancyServicesApi';

function getAccessToken(scheme, region, data){
    return new Promise((response, reject) => { 
        var api = new AuthenticationServicesApi()
        var callback = function(error, data, response) {
            if (error) {
                console.error(error);
                reject(error)
            } else {
                console.log('API called successfully. Returned data: ', data, response);
                resolve(data)
            }
        };
        
        api.tokenCreate(scheme, region, data, callback);
    });
}
/**
* API_services_to_automate_Deposit_Protection_within_your_existing_Property_Management_Software_workflows_and_applications_for_both_England__Wales_and_also_Scotland.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MydepositsDeveloperApi = require('index'); // See note below*.
* var xxxSvc = new MydepositsDeveloperApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MydepositsDeveloperApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MydepositsDeveloperApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MydepositsDeveloperApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.2.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The APIModelsBatch model constructor.
     * @property {module:model/APIModelsBatch}
     */
    APIModelsBatch,

    /**
     * The APIModelsBatchAddTenancy model constructor.
     * @property {module:model/APIModelsBatchAddTenancy}
     */
    APIModelsBatchAddTenancy,

    /**
     * The APIModelsBranch model constructor.
     * @property {module:model/APIModelsBranch}
     */
    APIModelsBranch,

    /**
     * The APIModelsCheckout model constructor.
     * @property {module:model/APIModelsCheckout}
     */
    APIModelsCheckout,

    /**
     * The APIModelsDeductions model constructor.
     * @property {module:model/APIModelsDeductions}
     */
    APIModelsDeductions,

    /**
     * The APIModelsInterestedParty model constructor.
     * @property {module:model/APIModelsInterestedParty}
     */
    APIModelsInterestedParty,

    /**
     * The APIModelsJointTenant model constructor.
     * @property {module:model/APIModelsJointTenant}
     */
    APIModelsJointTenant,

    /**
     * The APIModelsLandlord model constructor.
     * @property {module:model/APIModelsLandlord}
     */
    APIModelsLandlord,

    /**
     * The APIModelsLandlordMember model constructor.
     * @property {module:model/APIModelsLandlordMember}
     */
    APIModelsLandlordMember,

    /**
     * The APIModelsPaymentDetail model constructor.
     * @property {module:model/APIModelsPaymentDetail}
     */
    APIModelsPaymentDetail,

    /**
     * The APIModelsProperty model constructor.
     * @property {module:model/APIModelsProperty}
     */
    APIModelsProperty,

    /**
     * The APIModelsSubscribe model constructor.
     * @property {module:model/APIModelsSubscribe}
     */
    APIModelsSubscribe,

    /**
     * The APIModelsTenancy model constructor.
     * @property {module:model/APIModelsTenancy}
     */
    APIModelsTenancy,

    /**
     * The APIModelsTenant model constructor.
     * @property {module:model/APIModelsTenant}
     */
    APIModelsTenant,

    /**
     * The APIModelsToken model constructor.
     * @property {module:model/APIModelsToken}
     */
    APIModelsToken,

    /**
     * The APIModelsUnprotect model constructor.
     * @property {module:model/APIModelsUnprotect}
     */
    APIModelsUnprotect,

    /**
     * The APIModelsUnprotectAccept model constructor.
     * @property {module:model/APIModelsUnprotectAccept}
     */
    APIModelsUnprotectAccept,

    /**
     * The APIModelsUnprotectionDeductions model constructor.
     * @property {module:model/APIModelsUnprotectionDeductions}
     */
    APIModelsUnprotectionDeductions,

    /**
     * The APIResponsesBatch model constructor.
     * @property {module:model/APIResponsesBatch}
     */
    APIResponsesBatch,

    /**
     * The APIResponsesBatchAddTenancy model constructor.
     * @property {module:model/APIResponsesBatchAddTenancy}
     */
    APIResponsesBatchAddTenancy,

    /**
     * The APIResponsesBatchCheckout model constructor.
     * @property {module:model/APIResponsesBatchCheckout}
     */
    APIResponsesBatchCheckout,

    /**
     * The APIResponsesBatchDetails model constructor.
     * @property {module:model/APIResponsesBatchDetails}
     */
    APIResponsesBatchDetails,

    /**
     * The APIResponsesBatchList model constructor.
     * @property {module:model/APIResponsesBatchList}
     */
    APIResponsesBatchList,

    /**
     * The APIResponsesBatchTenancy model constructor.
     * @property {module:model/APIResponsesBatchTenancy}
     */
    APIResponsesBatchTenancy,

    /**
     * The APIResponsesBranch model constructor.
     * @property {module:model/APIResponsesBranch}
     */
    APIResponsesBranch,

    /**
     * The APIResponsesBranchDetails model constructor.
     * @property {module:model/APIResponsesBranchDetails}
     */
    APIResponsesBranchDetails,

    /**
     * The APIResponsesBranchList model constructor.
     * @property {module:model/APIResponsesBranchList}
     */
    APIResponsesBranchList,

    /**
     * The APIResponsesCheckout model constructor.
     * @property {module:model/APIResponsesCheckout}
     */
    APIResponsesCheckout,

    /**
     * The APIResponsesConvertSPT model constructor.
     * @property {module:model/APIResponsesConvertSPT}
     */
    APIResponsesConvertSPT,

    /**
     * The APIResponsesDefaultPayment model constructor.
     * @property {module:model/APIResponsesDefaultPayment}
     */
    APIResponsesDefaultPayment,

    /**
     * The APIResponsesErrorList model constructor.
     * @property {module:model/APIResponsesErrorList}
     */
    APIResponsesErrorList,

    /**
     * The APIResponsesErrors model constructor.
     * @property {module:model/APIResponsesErrors}
     */
    APIResponsesErrors,

    /**
     * The APIResponsesInterestedPartyDetails model constructor.
     * @property {module:model/APIResponsesInterestedPartyDetails}
     */
    APIResponsesInterestedPartyDetails,

    /**
     * The APIResponsesJointTenant model constructor.
     * @property {module:model/APIResponsesJointTenant}
     */
    APIResponsesJointTenant,

    /**
     * The APIResponsesLandlord model constructor.
     * @property {module:model/APIResponsesLandlord}
     */
    APIResponsesLandlord,

    /**
     * The APIResponsesLandlordDetails model constructor.
     * @property {module:model/APIResponsesLandlordDetails}
     */
    APIResponsesLandlordDetails,

    /**
     * The APIResponsesLandlordMember model constructor.
     * @property {module:model/APIResponsesLandlordMember}
     */
    APIResponsesLandlordMember,

    /**
     * The APIResponsesLeadTenant model constructor.
     * @property {module:model/APIResponsesLeadTenant}
     */
    APIResponsesLeadTenant,

    /**
     * The APIResponsesOTP model constructor.
     * @property {module:model/APIResponsesOTP}
     */
    APIResponsesOTP,

    /**
     * The APIResponsesPaymentDetail model constructor.
     * @property {module:model/APIResponsesPaymentDetail}
     */
    APIResponsesPaymentDetail,

    /**
     * The APIResponsesPaymentDetails model constructor.
     * @property {module:model/APIResponsesPaymentDetails}
     */
    APIResponsesPaymentDetails,

    /**
     * The APIResponsesPaymentDetailsList model constructor.
     * @property {module:model/APIResponsesPaymentDetailsList}
     */
    APIResponsesPaymentDetailsList,

    /**
     * The APIResponsesProperty model constructor.
     * @property {module:model/APIResponsesProperty}
     */
    APIResponsesProperty,

    /**
     * The APIResponsesPropertyDetails model constructor.
     * @property {module:model/APIResponsesPropertyDetails}
     */
    APIResponsesPropertyDetails,

    /**
     * The APIResponsesProtection model constructor.
     * @property {module:model/APIResponsesProtection}
     */
    APIResponsesProtection,

    /**
     * The APIResponsesProtectionList model constructor.
     * @property {module:model/APIResponsesProtectionList}
     */
    APIResponsesProtectionList,

    /**
     * The APIResponsesSchemeRules model constructor.
     * @property {module:model/APIResponsesSchemeRules}
     */
    APIResponsesSchemeRules,

    /**
     * The APIResponsesTenancy model constructor.
     * @property {module:model/APIResponsesTenancy}
     */
    APIResponsesTenancy,

    /**
     * The APIResponsesTenancyDetails model constructor.
     * @property {module:model/APIResponsesTenancyDetails}
     */
    APIResponsesTenancyDetails,

    /**
     * The APIResponsesToken model constructor.
     * @property {module:model/APIResponsesToken}
     */
    APIResponsesToken,

    /**
     * The APIResponsesUnprotect model constructor.
     * @property {module:model/APIResponsesUnprotect}
     */
    APIResponsesUnprotect,

    /**
     * The Country model constructor.
     * @property {module:model/Country}
     */
    Country,

    /**
     * The DeductionReasons model constructor.
     * @property {module:model/DeductionReasons}
     */
    DeductionReasons,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The LocalAuthorityRegion model constructor.
     * @property {module:model/LocalAuthorityRegion}
     */
    LocalAuthorityRegion,

    /**
     * The PropertyType model constructor.
     * @property {module:model/PropertyType}
     */
    PropertyType,

    /**
     * The TenancyStatus model constructor.
     * @property {module:model/TenancyStatus}
     */
    TenancyStatus,

    /**
     * The TenancyType model constructor.
     * @property {module:model/TenancyType}
     */
    TenancyType,

    /**
     * The Title model constructor.
     * @property {module:model/Title}
     */
    Title,

    /**
    * The AuthenticationServicesApi service constructor.
    * @property {module:api/AuthenticationServicesApi}
    */
    AuthenticationServicesApi,

    /**
    * The BatchServicesApi service constructor.
    * @property {module:api/BatchServicesApi}
    */
    BatchServicesApi,

    /**
    * The GlobalServicesApi service constructor.
    * @property {module:api/GlobalServicesApi}
    */
    GlobalServicesApi,

    /**
    * The LandlordServicesApi service constructor.
    * @property {module:api/LandlordServicesApi}
    */
    LandlordServicesApi,

    /**
    * The MemberAccountServicesApi service constructor.
    * @property {module:api/MemberAccountServicesApi}
    */
    MemberAccountServicesApi,

    /**
    * The PropertyServicesApi service constructor.
    * @property {module:api/PropertyServicesApi}
    */
    PropertyServicesApi,

    /**
    * The TenancyServicesApi service constructor.
    * @property {module:api/TenancyServicesApi}
    */
    TenancyServicesApi,

    /**
    * Get Access token methos.
    */
    getAccessToken
};
