/**
 * mydeposits - Developer API
 * API services to automate Deposit Protection within your existing Property Management Software workflows and applications for both England & Wales, and also Scotland
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: api@mydeposits.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MydepositsDeveloperApi);
  }
}(this, function(expect, MydepositsDeveloperApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MydepositsDeveloperApi.TenancyServicesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TenancyServicesApi', function() {
    describe('tenancyCertificate', function() {
      it('should call tenancyCertificate successfully', function(done) {
        //uncomment below and update the code to test tenancyCertificate
        //instance.tenancyCertificate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenancyCheckout', function() {
      it('should call tenancyCheckout successfully', function(done) {
        //uncomment below and update the code to test tenancyCheckout
        //instance.tenancyCheckout(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenancyGet', function() {
      it('should call tenancyGet successfully', function(done) {
        //uncomment below and update the code to test tenancyGet
        //instance.tenancyGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenancyGetList', function() {
      it('should call tenancyGetList successfully', function(done) {
        //uncomment below and update the code to test tenancyGetList
        //instance.tenancyGetList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenancyPost', function() {
      it('should call tenancyPost successfully', function(done) {
        //uncomment below and update the code to test tenancyPost
        //instance.tenancyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenancyUnprotect', function() {
      it('should call tenancyUnprotect successfully', function(done) {
        //uncomment below and update the code to test tenancyUnprotect
        //instance.tenancyUnprotect(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenancyUnprotectAccept', function() {
      it('should call tenancyUnprotectAccept successfully', function(done) {
        //uncomment below and update the code to test tenancyUnprotectAccept
        //instance.tenancyUnprotectAccept(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenancyUnprotectCounter', function() {
      it('should call tenancyUnprotectCounter successfully', function(done) {
        //uncomment below and update the code to test tenancyUnprotectCounter
        //instance.tenancyUnprotectCounter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenancyUnprotectOTP', function() {
      it('should call tenancyUnprotectOTP successfully', function(done) {
        //uncomment below and update the code to test tenancyUnprotectOTP
        //instance.tenancyUnprotectOTP(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tenancyUnprotectSPT', function() {
      it('should call tenancyUnprotectSPT successfully', function(done) {
        //uncomment below and update the code to test tenancyUnprotectSPT
        //instance.tenancyUnprotectSPT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
